### ISSUE TITLE
Submitting new evidence items fails on local instance with subscription related error

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#70]
I have reproduced this on two local installs that are using the latest version of everything:

If I submit a new evidence item everything seems to work fine.  I then log into the admin interface to approve the new submission and find that the new evidence item is missing the gene and variant info I entered and has status `failed`:

![screen shot 2015-07-02 at 11 46 00 am](https://cloud.githubusercontent.com/assets/856728/8482570/22707734-20b0-11e5-93ff-71374f5b9a43.png)

@jmcmichael helped me track down what looks like the relevant error message in `civic-server/log/development.log`:

```
  EvidenceItem Load (0.4ms)  SELECT  "evidence_items".* FROM "evidence_items" WHERE "evidence_items"."deleted" = 'f' AND "evidence_items"."id" = $1 LIMIT 1  [["id", 433]]
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9] Performing ValidateProposedEvidenceItem from DelayedJob(default) with arguments: gid://civic-server/EvidenceItem/433
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]   Gene Load (0.4ms)  SELECT  "genes".* FROM "genes" WHERE "genes"."deleted" = 'f' AND "genes"."entrez_id" = $1 LIMIT 1  [["entrez_id", 673]]
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]   Source Load (0.5ms)  SELECT  "sources".* FROM "sources" WHERE "sources"."pubmed_id" = $1 LIMIT 1  [["pubmed_id", "23463675"]]
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]   Disease Load (0.3ms)  SELECT  "diseases".* FROM "diseases" WHERE "diseases"."doid" = $1 LIMIT 1  [["doid", "1909"]]
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]    (0.1ms)  BEGIN
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]    (0.5ms)  SELECT MAX("audits"."version") FROM "audits" WHERE "audits"."auditable_id" = $1 AND "audits"."auditable_type" = $2  [["auditable_id", 433], ["auditable_type", "EvidenceItem"]]
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]   SQL (0.4ms)  INSERT INTO "audits" ("action", "audited_changes", "auditable_id", "auditable_type", "created_at", "version", "request_uuid") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["action", "update"], ["audited_changes", "---\nremote_errors:\n- \n- variant_name: No variant_name provided\nstatus:\n- submitted\n- failed\n"], ["auditable_id", 433], ["auditable_type", "EvidenceItem"], ["created_at", "2015-07-02 16:41:29.852864"], ["version", 2], ["request_uuid", "a9aabc67-f31d-4e68-9722-070d1df1e36c"]]
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]   SQL (0.4ms)  UPDATE "evidence_items" SET "remote_errors" = $1, "status" = $2, "updated_at" = $3 WHERE "evidence_items"."id" = $4  [["remote_errors", "{\"variant_name\":\"No variant_name provided\"}"], ["status", "failed"], ["updated_at", "2015-07-02 16:41:29.847825"], ["id", 433]]
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9]    (0.5ms)  COMMIT
[ActiveJob] [ValidateProposedEvidenceItem] [67c34fed-c041-4a6f-a07a-a5dfe52c10b9] Performed ValidateProposedEvidenceItem from DelayedJob(default) in 28.25ms
   (0.1ms)  BEGIN
  SQL (0.3ms)  DELETE FROM "delayed_jobs" WHERE "delayed_jobs"."id" = $1  [["id", 3]]
   (0.3ms)  COMMIT
2015-07-02T11:41:29-0500: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:32289)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=3) COMPLETED after 0.0400
  Delayed::Backend::ActiveRecord::Job Load (0.9ms)  UPDATE "delayed_jobs" SET locked_at = '2015-07-02 16:41:29.860120', locked_by = 'delayed_job host:Malachis-MacBook-Pro.local pid:32289' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2015-07-02 16:41:29.859731' AND (locked_at IS NULL OR locked_at < '2015-07-02 12:41:29.859783') OR locked_by = 'delayed_job host:Malachis-MacBook-Pro.local pid:32289') AND failed_at IS NULL)  ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
2015-07-02T11:41:29-0500: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:32289)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=4) RUNNING
  Event Load (0.2ms)  SELECT  "events".* FROM "events" WHERE "events"."id" = $1 LIMIT 1  [["id", 2]]
[ActiveJob] [NotifySubscribers] [bd75c956-6221-4ca2-9ca3-1e29a1755803] Performing NotifySubscribers from DelayedJob(default) with arguments: gid://civic-server/Event/2
[ActiveJob] [NotifySubscribers] [bd75c956-6221-4ca2-9ca3-1e29a1755803]   EvidenceItem Load (0.3ms)  SELECT  "evidence_items".* FROM "evidence_items" WHERE "evidence_items"."id" = $1 LIMIT 1  [["id", 433]]
[ActiveJob] [NotifySubscribers] [bd75c956-6221-4ca2-9ca3-1e29a1755803]   Subscription Load (0.2ms)  SELECT "subscriptions".* FROM "subscriptions" WHERE "subscriptions"."subscribable_id" = $1 AND "subscriptions"."subscribable_type" = $2  [["subscribable_id", 433], ["subscribable_type", "EvidenceItem"]]
[ActiveJob] [NotifySubscribers] [bd75c956-6221-4ca2-9ca3-1e29a1755803] Performed NotifySubscribers from DelayedJob(default) in 5.47ms
2015-07-02T11:41:29-0500: [Worker(delayed_job host:Malachis-MacBook-Pro.local pid:32289)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=4) FAILED (0 prior attempts) with NoMethodError: undefined method `subscriptions' for nil:NilClass
   (0.2ms)  BEGIN
  SQL (0.7ms)  UPDATE "delayed_jobs" SET "last_error" = $1, "attempts" = $2, "run_at" = $3, "locked_at" = $4, "locked_by" = $5, "updated_at" = $6 WHERE "delayed_jobs"."id" = $7  [["last_error", "undefined method `subscriptions' for nil:NilClass\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:13:in `block in aggregate_direct_subscriptions'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:12:in `tap'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:12:in `aggregate_direct_subscriptions'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:17:in `block (2 levels) in aggregate_direct_subscriptions'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:16:in `each'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:16:in `block in aggregate_direct_subscriptions'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:12:in `tap'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:12:in `aggregate_direct_subscriptions'\n/Users/mgriffit/git/civic/civic-server/app/jobs/notify_subscribers.rb:3:in `perform'\n/Users/mgriffit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/execution.rb:32:in `block in perform_now'\n/Users/mgriffit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'\n/Users/mgriffit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'\n/Users/mgriffit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in 
```

**Comment by acoffman** [comment]
Fixed in latest master!
